apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend-deployment
  labels:
    app: mern-frontend
  namespace: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend

    spec:
      containers:
        - name: mern-frontend
          image: rj1608/mern-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
