kind: Service
apiVersion: v1
metadata:
  name: mern-frontend-service
  namespace: mern-app
spec:
  selector:
    app: mern-frontend
  # ports:
  #   - port: 80
  #     targetPort: 80
  #     nodePort: 30001
  # type: NodePort
    ports:
    - port: 80
      targetPort: 80   # Your app container port
  type: LoadBalancer